easy_admin:
    design:
        menu:
            - { label: 'Home',  route: 'home', icon: home }
            - label: 'User'
              entity: User
            - label: 'Homepage'
              entity: HomePageText
#              icon: 'sign'
            - label: 'Professor'
              entity: Professor
#              icon: 'globe-americas'
            - label: 'Dojo'
              entity: Dojo
#              icon: 'palette'
            - label: 'Course'
              entity: Course
#              icon: 'wine-bottle'
#            - label: 'Other'
            - label: 'Schedules'
              entity: Schedules
#              icon: 'tint'
            - label: 'Links'
              entity: Link
#              icon: 'user-tie'
#            - label: 'Producer'
#              entity: Producer
#              icon: 'building'
