easy_admin:
    design:
        menu:
            - { label: 'Home',  route: 'home', icon: home }
            - label: 'User'
              entity: User
            - label: 'Homepage'
              entity: HomePageText
#              icon: 'sign'
            - label: 'Professor'
              entity: Professor
#              icon: 'globe-americas'
            - label: 'Dojo'
              entity: Dojo
#              icon: 'palette'
#            - label: 'Wine'
#              entity: Wine
#              icon: 'wine-bottle'
#            - label: 'Other'
#            - label: 'Beverage'
#              entity: Beverage
#              icon: 'tint'
#            - label: 'Professional'
#              entity: Professional
#              icon: 'user-tie'
#            - label: 'Producer'
#              entity: Producer
#              icon: 'building'
