easy_admin:
  entities:
    HomePageText:
      class: App\Entity\HomePageText
      form:
        fields:
          - { property: 'title' }
          - { property: 'paragraph' }

      list:
        fields:
          - { property: 'title' }
