easy_admin:
  entities:
    Professor:
      class: App\Entity\Professor
      form:
        fields:
          - { property: 'firstName' }
          - { property: 'lastName' }
          - { property: 'grade' }

      list:
        fields:
          - { property: 'firstName' }
          - { property: 'lastName' }
          - { property: 'grade' }