easy_admin:
    entities:
          User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'email' }
                    - { property: 'password' }

            list:
                fields:
                    - { property: 'email' }
                    - { property: 'password' }

